config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :invoice
  resources :user
  resources :payee
  root to: 'invoice#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    before_create :randomize_id
    belongs_to :user
    has_many :items
    has_one :invoice_payee
    has_one :payee, :through => :invoice_payee

    private
    def randomize_id
        begin
            self.id = SecureRandom.random_number(1_000_000)
        end while Invoice.where(id: self.id).exists?
    end
end

app/models/invoice_payee.rb
class InvoicePayee < ApplicationRecord
    belongs_to :payee
    belongs_to :invoice
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :invoice
end

app/models/payee.rb
class Payee < ApplicationRecord
    has_many :invoice_payees
    has_many :invoices, :through => :invoice_payees
end

app/models/user.rb
class User < ApplicationRecord
    has_many :invoices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoice_controller.rb
class InvoiceController < ApplicationController
    def index
        # Only support one user per deployment.
        @invoices = User.first.invoices.order("created_at DESC")
        @user = User.first

    end

    def new
        @invoice = Invoice.new
    end

    def show
        @invoice = Invoice.find(params[:id])
        respond_to do |format|
            format.html
            format.pdf do
                render pdf: "Invoice #{@invoice.id}"   # Excluding ".pdf" extension.
            end
        end
    end

    def create
        @payee = Payee.find(params[:invoice][:payee][:payee_id])
        # Holy fuck, what a hack
        params[:invoice].delete(:payee)
        @invoice = Invoice.create(invoice_params.merge(user_id: User.first.id))
        @ip = InvoicePayee.create(invoice_id: @invoice.id, payee_id: @payee.id)
        
        if @invoice.save
            @ip.save
            redirect_to invoice_path(@invoice), notice: "Invoice created"
        else
            redirect_to new_invoice_path, notice: "An error occurred."
        end
        
    end

    private

    def invoice_params
        
        params.require(:invoice).permit(:total, :notes)
    end
end

app/controllers/payee_controller.rb
class PayeeController < ApplicationController
    def index
        @payees = Payee.all
        @payee = Payee.new
    end

    def show
        @payee = Payee.find(params[:id])
    end

    def new
        @payee = Payee.new
    end

    def update
        @payee = Payee.find(params[:id])
        if @payee.update(payee_params)
            redirect_to payee_path(@payee), notice: 'Payee updated'
        else
            redirect_to payee_path(@payee), notice: 'Error occurred'

        end

    end

    def create
        @payee = Payee.create(payee_params)
        if @payee.save
            redirect_to payee_path(@payee), notice: 'Payee updated'
        else
            redirect_to payee_path(@payee), notice: 'Error occurred'

        end

    end

    private

    def payee_params
        params.require(:payee).permit(:name, :company, :phone, :email, :address)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def show
        @user = User.find(params[:id])

    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user), notice: 'Successfully updated'
        else
            redirect_to user_path(@user), notice: 'Error occurred' 
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :company_name, :address, :abn, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/payee_helper.rb
module PayeeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/invoice/index.slim
h3 Invoices
div class="d-flex flex-wrap"
    - @invoices.each do |i|
        div class="card" style="width: 18rem; margin: 2px"
            div class="card-body"
                h5 class="card-title" Invoice #{i.id}
                h6 class="card-subtitle mb-2 text-muted" = i.created_at.to_date 
                p class="card-text" Amount #{i.total}
                p class="card-text" Bill to #{i.payee.name}
                = link_to 'View HTML', invoice_path(i.id), class: "card-link"
                = link_to 'View PDF', invoice_path(i.id) + '.pdf', class: "card-link"

app/views/invoice/new.slim
h3 Generate a new invoice
= form_with model: @invoice, url: '/invoice', local: true do |form|
   
    div class="field"
      = form.label :total
      = form.text_field :total

    div class="field"
      = form.label :notes
      = form.text_area :notes

    div class="field"
        = form.label :payee
        = form.fields_for :payee do |p|
            = p.collection_select(:payee_id, Payee.all, :id, :name)

    table
        tr
            th Description
            th Hours
            th Rate
            th Amount
        tr
            /td = form.text_area @invoice





    = form.submit 'Create invoice' 

app/views/invoice/show.slim
div style="display: flex; justify-content: space-between"
    div 
        h2= @invoice.user.name
        p ABN: #{@invoice.user.abn} 
        p= @invoice.user.address
        p= @invoice.user.phone
        p= @invoice.user.company_name
        p= @invoice.user.email

    div
        h1 Tax Invoice



hr

div style="display: flex; justify-content: space-between"
    div
        p Bill to #{@invoice.payee.name }
        p = @invoice.notes
    
    div
        p
        b Invoice Number
        | #{@invoice.id}
        p
        b Invoice Date
        | #{@invoice.created_at}

table class="table table-striped"
    thead class="thead-dark"
        tr
            th scope="col" Description
            th scope="col" Hours
            th scope="col" Rate
            th scope="col" Amount

    - @invoice.items.each do |i|
        tr 
            td = i.description
            td = i.hours
            td = i.rate
            td #{i.hours * i.rate}

    tr
        th
        th  
        th Total
        th = @invoice.total

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoice Generator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Invoice Generator', '/', class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to User.first.name, user_path(User.first), class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Payees', payee_index_path, class: 'nav-link' %>
          </li>
        </ul>
        <span class="navbar-text">
          <%# Add   %>
        </span>
      </div>
    </nav>
    <div class="container">
      <%= notice %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.slim
body style="padding: 20px"
    div style="display: flex; justify-content: space-between"
        div 
            h2= @invoice.user.name
            p ABN: #{@invoice.user.abn} 
            p= @invoice.user.address
            p= @invoice.user.phone
            p= @invoice.user.company_name
            p= @invoice.user.email

        div
            h1 Tax Invoice



    hr

    div style="display: flex; justify-content: space-between"
        div
            p Bill to #{@invoice.payee.name }
            p = @invoice.notes
        
        div
            p
            b Invoice Number
            | #{@invoice.id}
            p
            b Invoice Date
            | #{@invoice.created_at}

    table class="table table-striped"
        thead class="thead-dark"
            tr
                th scope="col" Description
                th scope="col" Hours
                th scope="col" Rate
                th scope="col" Amount

        - @invoice.items.each do |i|
            tr 
                td = i.description
                td = i.hours
                td = i.rate
                td #{i.hours * i.rate}

        tr
            th
            th  
            th Total
            th = @invoice.total

app/views/payee/index.slim
h3 Create a payee
p Payees are people who you charge your invoice to. 
= form_for @payee, url: '/payee', local: true do |form|
   
    div class="form-group"
      = form.label :name
      = form.text_field :name, class: "form-control"

    div class="form-group"
      = form.label :email
      = form.text_field :email, class: "form-control"


    div class="form-group"
      = form.label :phone
      = form.text_field :phone, class: "form-control"

    div class="form-group"
      = form.label :address
      = form.text_field :address, class: "form-control"

    div class="form-group"
      = form.label :company
      = form.text_field :company, class: "form-control"


    = form.submit 'Create payee', class: "btn btn-primary" 

h3 Existing payees
div class="d-flex flex-wrap"
  - @payees.each do |p|
      div class="card" style="width: 18rem; margin: 2px"
          div class="card-body"
              h5 class="card-title" = p.name
              h6 class="card-subtitle mb-2 text-muted" = p.email
              p class="card-text" = p.phone
              p class="card-text" = p.company
              p class="card-text" = p.address
              = link_to 'View payee', payee_path(p.id), class: "card-link"

app/views/payee/show.slim
h3 Change payee details
= form_with model: @payee, local: true do |form|

   
    div class="form-group"
      = form.label :name
      = form.text_field :name, class: "form-control"

    div class="form-group"
      = form.label :email
      = form.text_field :email, class: "form-control"


    div class="form-group"
      = form.label :phone
      = form.text_field :phone, class: "form-control"

    div class="form-group"
      = form.label :address
      = form.text_field :address, class: "form-control"

    div class="form-group"
      = form.label :company
      = form.text_field :company, class: "form-control"


    = form.submit 'Update payee', class: "btn btn-primary" 

app/views/user/show.slim
h3 Change your details
= form_with model: @user, local: true do |form|

   
    div class="form-group"
      = form.label :name
      = form.text_field :name, class: "form-control"

    /div class="field"
      = form.label :company_name
      = form.text_field :company_name

    div class="form-group"
      = form.label :email
      = form.text_field :email, class: "form-control"

    div class="form-group"
      = form.label :abn, "ABN Number"
      = form.text_field :abn, class: "form-control"


    div class="form-group"
      = form.label :phone
      = form.text_field :phone, class: "form-control"

    div class="form-group"
      = form.label :address
      = form.text_field :address, class: "form-control"


    = form.submit 'Update user', class: "btn btn-primary" 